// <auto-generated />
using System;
using Hackaton.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hackaton.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211126191551_PuebraInicial")]
    partial class PuebraInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Hackaton.App.Dominio.Migrante", b =>
                {
                    b.Property<int>("MigranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correoE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<long>("identificacion")
                        .HasColumnType("bigint");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paisOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sitLaboral")
                        .HasColumnType("int");

                    b.Property<long>("telefono")
                        .HasColumnType("bigint");

                    b.Property<int>("tipoId")
                        .HasColumnType("int");

                    b.HasKey("MigranteId");

                    b.ToTable("Migrantes");
                });
#pragma warning restore 612, 618
        }
    }
}
